services:
  # PostgreSQL baza podataka
  - type: pserv
    name: myproperty-db
    env: postgres
    plan: free
    ipAllowList: []
    envVars:
      - key: POSTGRES_DB
        value: real_estate
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true

  # REST API
  - type: web
    name: myproperty-api
    env: dotnet
    plan: free
    runtime: dotnet-8
    repo: https://github.com/amx100/myproperty
    branch: main
    rootDir: api/MyProperty.API
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/MyProperty.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - fromService:
          name: myproperty-db
          property: connectionString
        key: ConnectionStrings__MainDB
      - key: JWTSettings__securityKey
        value: 7T-d1gfnZ_RqrWVHQYOo8ESZXDwwvPQ8ymWNGqFEm0c
      - key: JWTSettings__validIssuer
        value: https://myproperty-api.onrender.com
      - key: JWTSettings__validAudience
        value: https://myproperty-ui.onrender.com
      - key: JWTSettings__expiryInMinutes
        value: "10"
    headers:
      - path: /api
        name: Access-Control-Allow-Origin
        value: "https://myproperty-ui.onrender.com"

  # Blazor WebAssembly UI (Static Site)
  - type: web
    name: myproperty-ui
    env: static
    plan: free
    repo: https://github.com/amx100/myproperty
    branch: main
    rootDir: ui/MyProperty.UI/MyProperty.UI
    buildCommand: dotnet publish -c Release -o dist/wwwroot
    staticPublishPath: dist/wwwroot
